package com.hib.mappings;
// Generated Dec 30, 2015 2:12:59 PM by Hibernate Tools 3.6.0



/**
 * Chatmessages generated by hbm2java
 */
public class Chatmessages  implements java.io.Serializable {


     private Integer msgId;
     private User userByMsgFrom;
     private User userByMsgTo;
     private Userthreads userthreads;
     private String message;
     private boolean seen;
     private String date;

    public Chatmessages() {
    }

	
    public Chatmessages(User userByMsgFrom, User userByMsgTo, Userthreads userthreads, boolean seen) {
        this.userByMsgFrom = userByMsgFrom;
        this.userByMsgTo = userByMsgTo;
        this.userthreads = userthreads;
        this.seen = seen;
    }
    public Chatmessages(User userByMsgFrom, User userByMsgTo, Userthreads userthreads, String message, boolean seen, String date) {
       this.userByMsgFrom = userByMsgFrom;
       this.userByMsgTo = userByMsgTo;
       this.userthreads = userthreads;
       this.message = message;
       this.seen = seen;
       this.date = date;
    }
   
    public Integer getMsgId() {
        return this.msgId;
    }
    
    public void setMsgId(Integer msgId) {
        this.msgId = msgId;
    }
    public User getUserByMsgFrom() {
        return this.userByMsgFrom;
    }
    
    public void setUserByMsgFrom(User userByMsgFrom) {
        this.userByMsgFrom = userByMsgFrom;
    }
    public User getUserByMsgTo() {
        return this.userByMsgTo;
    }
    
    public void setUserByMsgTo(User userByMsgTo) {
        this.userByMsgTo = userByMsgTo;
    }
    public Userthreads getUserthreads() {
        return this.userthreads;
    }
    
    public void setUserthreads(Userthreads userthreads) {
        this.userthreads = userthreads;
    }
    public String getMessage() {
        return this.message;
    }
    
    public void setMessage(String message) {
        this.message = message;
    }
    public boolean isSeen() {
        return this.seen;
    }
    
    public void setSeen(boolean seen) {
        this.seen = seen;
    }
    public String getDate() {
        return this.date;
    }
    
    public void setDate(String date) {
        this.date = date;
    }




}


