package com.hib.mappings;
// Generated Dec 30, 2015 2:12:59 PM by Hibernate Tools 3.6.0



/**
 * ContactUs generated by hbm2java
 */
public class ContactUs  implements java.io.Serializable {


     private Integer idcontactUs;
     private String subName;
     private String subEmail;
     private String topic;
     private String description;

    public ContactUs() {
    }

    public ContactUs(String subName, String subEmail, String topic, String description) {
       this.subName = subName;
       this.subEmail = subEmail;
       this.topic = topic;
       this.description = description;
    }
   
    public Integer getIdcontactUs() {
        return this.idcontactUs;
    }
    
    public void setIdcontactUs(Integer idcontactUs) {
        this.idcontactUs = idcontactUs;
    }
    public String getSubName() {
        return this.subName;
    }
    
    public void setSubName(String subName) {
        this.subName = subName;
    }
    public String getSubEmail() {
        return this.subEmail;
    }
    
    public void setSubEmail(String subEmail) {
        this.subEmail = subEmail;
    }
    public String getTopic() {
        return this.topic;
    }
    
    public void setTopic(String topic) {
        this.topic = topic;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }




}


