package com.hib.mappings;
// Generated Dec 30, 2015 2:12:59 PM by Hibernate Tools 3.6.0



/**
 * Feedback generated by hbm2java
 */
public class Feedback  implements java.io.Serializable {


     private Integer idfeedback;
     private Integer userId;
     private String details;
     private String date;

    public Feedback() {
    }

    public Feedback(Integer userId, String details, String date) {
       this.userId = userId;
       this.details = details;
       this.date = date;
    }
   
    public Integer getIdfeedback() {
        return this.idfeedback;
    }
    
    public void setIdfeedback(Integer idfeedback) {
        this.idfeedback = idfeedback;
    }
    public Integer getUserId() {
        return this.userId;
    }
    
    public void setUserId(Integer userId) {
        this.userId = userId;
    }
    public String getDetails() {
        return this.details;
    }
    
    public void setDetails(String details) {
        this.details = details;
    }
    public String getDate() {
        return this.date;
    }
    
    public void setDate(String date) {
        this.date = date;
    }




}


