package com.hib.mappings;
// Generated Dec 30, 2015 2:12:59 PM by Hibernate Tools 3.6.0



/**
 * Help generated by hbm2java
 */
public class Help  implements java.io.Serializable {


     private Integer idhelp;
     private Integer userId;
     private String topic;
     private String details;
     private String date;

    public Help() {
    }

    public Help(Integer userId, String topic, String details, String date) {
       this.userId = userId;
       this.topic = topic;
       this.details = details;
       this.date = date;
    }
   
    public Integer getIdhelp() {
        return this.idhelp;
    }
    
    public void setIdhelp(Integer idhelp) {
        this.idhelp = idhelp;
    }
    public Integer getUserId() {
        return this.userId;
    }
    
    public void setUserId(Integer userId) {
        this.userId = userId;
    }
    public String getTopic() {
        return this.topic;
    }
    
    public void setTopic(String topic) {
        this.topic = topic;
    }
    public String getDetails() {
        return this.details;
    }
    
    public void setDetails(String details) {
        this.details = details;
    }
    public String getDate() {
        return this.date;
    }
    
    public void setDate(String date) {
        this.date = date;
    }




}


