package com.hib.mappings;
// Generated Dec 30, 2015 2:12:59 PM by Hibernate Tools 3.6.0



/**
 * Usernotification generated by hbm2java
 */
public class Usernotification  implements java.io.Serializable {


     private Integer iduserNotification;
     private User user;
     private int userId;
     private String time;
     private String seen;

    public Usernotification() {
    }

    public Usernotification(User user, int userId, String time, String seen) {
       this.user = user;
       this.userId = userId;
       this.time = time;
       this.seen = seen;
    }
   
    public Integer getIduserNotification() {
        return this.iduserNotification;
    }
    
    public void setIduserNotification(Integer iduserNotification) {
        this.iduserNotification = iduserNotification;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    public int getUserId() {
        return this.userId;
    }
    
    public void setUserId(int userId) {
        this.userId = userId;
    }
    public String getTime() {
        return this.time;
    }
    
    public void setTime(String time) {
        this.time = time;
    }
    public String getSeen() {
        return this.seen;
    }
    
    public void setSeen(String seen) {
        this.seen = seen;
    }




}


