package com.hib.mappings;
// Generated Dec 30, 2015 2:12:59 PM by Hibernate Tools 3.6.0


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * User generated by hbm2java
 */
public class User  implements java.io.Serializable {


     private Integer iduser;
     private Usertypes usertypes;
     private Userlogin userlogin;
     private String fname;
     private String lname;
     private String gender;
     private Integer age;
     private String maritalStatus;
     private String mothertongue;
     private String caste;
     private String religion;
     private BigDecimal height;
     private String city;
     private String country;
     private String educationLevel;
     private String profession;
     private String workplace;
     private String income;
     private String yourself;
     private String background;
     private String educationStatus;
     private String wealth;
     private String expectations;
     private String email;
     private String fbEmail;
     private byte[] propicture;
     private Boolean activateStatus;
     private String fbProfile;
     private String userNameId;
     private String date;
     private Set chatmessagesesForMsgTo = new HashSet(0);
     private Set userrequestses = new HashSet(0);
     private Set usernotifications = new HashSet(0);
     private Set usersessions = new HashSet(0);
     private Set userthreadsesForUser1 = new HashSet(0);
     private Set chatmessagesesForMsgFrom = new HashSet(0);
     private Set userthreadsesForUser2 = new HashSet(0);
     private Set usergrantprivilegeses = new HashSet(0);

    public User() {
    }

    public User(Usertypes usertypes, Userlogin userlogin, String fname, String lname, String gender, Integer age, String maritalStatus, String mothertongue, String caste, String religion, BigDecimal height, String city, String country, String educationLevel, String profession, String workplace, String income, String yourself, String background, String educationStatus, String wealth, String expectations, String email, String fbEmail, byte[] propicture, Boolean activateStatus, String fbProfile, String userNameId, String date, Set chatmessagesesForMsgTo, Set userrequestses, Set usernotifications, Set usersessions, Set userthreadsesForUser1, Set chatmessagesesForMsgFrom, Set userthreadsesForUser2, Set usergrantprivilegeses) {
       this.usertypes = usertypes;
       this.userlogin = userlogin;
       this.fname = fname;
       this.lname = lname;
       this.gender = gender;
       this.age = age;
       this.maritalStatus = maritalStatus;
       this.mothertongue = mothertongue;
       this.caste = caste;
       this.religion = religion;
       this.height = height;
       this.city = city;
       this.country = country;
       this.educationLevel = educationLevel;
       this.profession = profession;
       this.workplace = workplace;
       this.income = income;
       this.yourself = yourself;
       this.background = background;
       this.educationStatus = educationStatus;
       this.wealth = wealth;
       this.expectations = expectations;
       this.email = email;
       this.fbEmail = fbEmail;
       this.propicture = propicture;
       this.activateStatus = activateStatus;
       this.fbProfile = fbProfile;
       this.userNameId = userNameId;
       this.date = date;
       this.chatmessagesesForMsgTo = chatmessagesesForMsgTo;
       this.userrequestses = userrequestses;
       this.usernotifications = usernotifications;
       this.usersessions = usersessions;
       this.userthreadsesForUser1 = userthreadsesForUser1;
       this.chatmessagesesForMsgFrom = chatmessagesesForMsgFrom;
       this.userthreadsesForUser2 = userthreadsesForUser2;
       this.usergrantprivilegeses = usergrantprivilegeses;
    }
   
    public Integer getIduser() {
        return this.iduser;
    }
    
    public void setIduser(Integer iduser) {
        this.iduser = iduser;
    }
    public Usertypes getUsertypes() {
        return this.usertypes;
    }
    
    public void setUsertypes(Usertypes usertypes) {
        this.usertypes = usertypes;
    }
    public Userlogin getUserlogin() {
        return this.userlogin;
    }
    
    public void setUserlogin(Userlogin userlogin) {
        this.userlogin = userlogin;
    }
    public String getFname() {
        return this.fname;
    }
    
    public void setFname(String fname) {
        this.fname = fname;
    }
    public String getLname() {
        return this.lname;
    }
    
    public void setLname(String lname) {
        this.lname = lname;
    }
    public String getGender() {
        return this.gender;
    }
    
    public void setGender(String gender) {
        this.gender = gender;
    }
    public Integer getAge() {
        return this.age;
    }
    
    public void setAge(Integer age) {
        this.age = age;
    }
    public String getMaritalStatus() {
        return this.maritalStatus;
    }
    
    public void setMaritalStatus(String maritalStatus) {
        this.maritalStatus = maritalStatus;
    }
    public String getMothertongue() {
        return this.mothertongue;
    }
    
    public void setMothertongue(String mothertongue) {
        this.mothertongue = mothertongue;
    }
    public String getCaste() {
        return this.caste;
    }
    
    public void setCaste(String caste) {
        this.caste = caste;
    }
    public String getReligion() {
        return this.religion;
    }
    
    public void setReligion(String religion) {
        this.religion = religion;
    }
    public BigDecimal getHeight() {
        return this.height;
    }
    
    public void setHeight(BigDecimal height) {
        this.height = height;
    }
    public String getCity() {
        return this.city;
    }
    
    public void setCity(String city) {
        this.city = city;
    }
    public String getCountry() {
        return this.country;
    }
    
    public void setCountry(String country) {
        this.country = country;
    }
    public String getEducationLevel() {
        return this.educationLevel;
    }
    
    public void setEducationLevel(String educationLevel) {
        this.educationLevel = educationLevel;
    }
    public String getProfession() {
        return this.profession;
    }
    
    public void setProfession(String profession) {
        this.profession = profession;
    }
    public String getWorkplace() {
        return this.workplace;
    }
    
    public void setWorkplace(String workplace) {
        this.workplace = workplace;
    }
    public String getIncome() {
        return this.income;
    }
    
    public void setIncome(String income) {
        this.income = income;
    }
    public String getYourself() {
        return this.yourself;
    }
    
    public void setYourself(String yourself) {
        this.yourself = yourself;
    }
    public String getBackground() {
        return this.background;
    }
    
    public void setBackground(String background) {
        this.background = background;
    }
    public String getEducationStatus() {
        return this.educationStatus;
    }
    
    public void setEducationStatus(String educationStatus) {
        this.educationStatus = educationStatus;
    }
    public String getWealth() {
        return this.wealth;
    }
    
    public void setWealth(String wealth) {
        this.wealth = wealth;
    }
    public String getExpectations() {
        return this.expectations;
    }
    
    public void setExpectations(String expectations) {
        this.expectations = expectations;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getFbEmail() {
        return this.fbEmail;
    }
    
    public void setFbEmail(String fbEmail) {
        this.fbEmail = fbEmail;
    }
    public byte[] getPropicture() {
        return this.propicture;
    }
    
    public void setPropicture(byte[] propicture) {
        this.propicture = propicture;
    }
    public Boolean getActivateStatus() {
        return this.activateStatus;
    }
    
    public void setActivateStatus(Boolean activateStatus) {
        this.activateStatus = activateStatus;
    }
    public String getFbProfile() {
        return this.fbProfile;
    }
    
    public void setFbProfile(String fbProfile) {
        this.fbProfile = fbProfile;
    }
    public String getUserNameId() {
        return this.userNameId;
    }
    
    public void setUserNameId(String userNameId) {
        this.userNameId = userNameId;
    }
    public String getDate() {
        return this.date;
    }
    
    public void setDate(String date) {
        this.date = date;
    }
    public Set getChatmessagesesForMsgTo() {
        return this.chatmessagesesForMsgTo;
    }
    
    public void setChatmessagesesForMsgTo(Set chatmessagesesForMsgTo) {
        this.chatmessagesesForMsgTo = chatmessagesesForMsgTo;
    }
    public Set getUserrequestses() {
        return this.userrequestses;
    }
    
    public void setUserrequestses(Set userrequestses) {
        this.userrequestses = userrequestses;
    }
    public Set getUsernotifications() {
        return this.usernotifications;
    }
    
    public void setUsernotifications(Set usernotifications) {
        this.usernotifications = usernotifications;
    }
    public Set getUsersessions() {
        return this.usersessions;
    }
    
    public void setUsersessions(Set usersessions) {
        this.usersessions = usersessions;
    }
    public Set getUserthreadsesForUser1() {
        return this.userthreadsesForUser1;
    }
    
    public void setUserthreadsesForUser1(Set userthreadsesForUser1) {
        this.userthreadsesForUser1 = userthreadsesForUser1;
    }
    public Set getChatmessagesesForMsgFrom() {
        return this.chatmessagesesForMsgFrom;
    }
    
    public void setChatmessagesesForMsgFrom(Set chatmessagesesForMsgFrom) {
        this.chatmessagesesForMsgFrom = chatmessagesesForMsgFrom;
    }
    public Set getUserthreadsesForUser2() {
        return this.userthreadsesForUser2;
    }
    
    public void setUserthreadsesForUser2(Set userthreadsesForUser2) {
        this.userthreadsesForUser2 = userthreadsesForUser2;
    }
    public Set getUsergrantprivilegeses() {
        return this.usergrantprivilegeses;
    }
    
    public void setUsergrantprivilegeses(Set usergrantprivilegeses) {
        this.usergrantprivilegeses = usergrantprivilegeses;
    }




}


