package com.hib.mappings;
// Generated Dec 30, 2015 2:12:59 PM by Hibernate Tools 3.6.0



/**
 * Usergrantprivileges generated by hbm2java
 */
public class Usergrantprivileges  implements java.io.Serializable {


     private Integer iduserGrantPrivileges;
     private User user;
     private String reqUserId;
     private boolean proPicture;
     private boolean username;
     private boolean workplace;
     private boolean email;
     private boolean fbProfile;

    public Usergrantprivileges() {
    }

    public Usergrantprivileges(User user, String reqUserId, boolean proPicture, boolean username, boolean workplace, boolean email, boolean fbProfile) {
       this.user = user;
       this.reqUserId = reqUserId;
       this.proPicture = proPicture;
       this.username = username;
       this.workplace = workplace;
       this.email = email;
       this.fbProfile = fbProfile;
    }
   
    public Integer getIduserGrantPrivileges() {
        return this.iduserGrantPrivileges;
    }
    
    public void setIduserGrantPrivileges(Integer iduserGrantPrivileges) {
        this.iduserGrantPrivileges = iduserGrantPrivileges;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    public String getReqUserId() {
        return this.reqUserId;
    }
    
    public void setReqUserId(String reqUserId) {
        this.reqUserId = reqUserId;
    }
    public boolean isProPicture() {
        return this.proPicture;
    }
    
    public void setProPicture(boolean proPicture) {
        this.proPicture = proPicture;
    }
    public boolean isUsername() {
        return this.username;
    }
    
    public void setUsername(boolean username) {
        this.username = username;
    }
    public boolean isWorkplace() {
        return this.workplace;
    }
    
    public void setWorkplace(boolean workplace) {
        this.workplace = workplace;
    }
    public boolean isEmail() {
        return this.email;
    }
    
    public void setEmail(boolean email) {
        this.email = email;
    }
    public boolean isFbProfile() {
        return this.fbProfile;
    }
    
    public void setFbProfile(boolean fbProfile) {
        this.fbProfile = fbProfile;
    }




}


