package com.hib.mappings;
// Generated Dec 30, 2015 2:12:59 PM by Hibernate Tools 3.6.0



/**
 * Usersession generated by hbm2java
 */
public class Usersession  implements java.io.Serializable {


     private Integer iduserSession;
     private User user;
     private Boolean status;

    public Usersession() {
    }

	
    public Usersession(User user) {
        this.user = user;
    }
    public Usersession(User user, Boolean status) {
       this.user = user;
       this.status = status;
    }
   
    public Integer getIduserSession() {
        return this.iduserSession;
    }
    
    public void setIduserSession(Integer iduserSession) {
        this.iduserSession = iduserSession;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    public Boolean getStatus() {
        return this.status;
    }
    
    public void setStatus(Boolean status) {
        this.status = status;
    }




}


