package com.hib.mappings;
// Generated Dec 30, 2015 2:12:59 PM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Usertypes generated by hbm2java
 */
public class Usertypes  implements java.io.Serializable {


     private Integer typeId;
     private String userTypes;
     private Set users = new HashSet(0);

    public Usertypes() {
    }

	
    public Usertypes(String userTypes) {
        this.userTypes = userTypes;
    }
    public Usertypes(String userTypes, Set users) {
       this.userTypes = userTypes;
       this.users = users;
    }
   
    public Integer getTypeId() {
        return this.typeId;
    }
    
    public void setTypeId(Integer typeId) {
        this.typeId = typeId;
    }
    public String getUserTypes() {
        return this.userTypes;
    }
    
    public void setUserTypes(String userTypes) {
        this.userTypes = userTypes;
    }
    public Set getUsers() {
        return this.users;
    }
    
    public void setUsers(Set users) {
        this.users = users;
    }




}


