package com.hib.mappings;
// Generated Dec 30, 2015 2:12:59 PM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Userlogin generated by hbm2java
 */
public class Userlogin  implements java.io.Serializable {


     private Integer loginId;
     private String userName;
     private String password;
     private Set users = new HashSet(0);

    public Userlogin() {
    }

    public Userlogin(String userName, String password, Set users) {
       this.userName = userName;
       this.password = password;
       this.users = users;
    }
   
    public Integer getLoginId() {
        return this.loginId;
    }
    
    public void setLoginId(Integer loginId) {
        this.loginId = loginId;
    }
    public String getUserName() {
        return this.userName;
    }
    
    public void setUserName(String userName) {
        this.userName = userName;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public Set getUsers() {
        return this.users;
    }
    
    public void setUsers(Set users) {
        this.users = users;
    }




}


